FROM node:20-alpine AS frontend_build
WORKDIR /frontend 

COPY app/package*.json ./
RUN npm ci --legacy-peer-deps

COPY app/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=frontend_build /frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
